[tool.poetry]
name = "anamoly_detection"
version = "0.1.0"
description = ""
authors = ["{{vinay}} <{{vinaykanuku7565@gmail.com}}>"]
[tool.poetry.dependencies]
python = "^3.10"
[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
